### ISSUE TITLE
It would be good to have target directory option

### ISSUE THREAD

**Issue by podviaznikov** [martinklepsch/boot-gzip#1]
I think what I want is just specify directory and expect boot-gzip to gzip all files and append `.gz` to all of them.
It's not possible right now, correct? Do you think this use case would be valuable?

**Comment by martinklepsch** [comment]
My initial idea was that users could just generate the mapping on their own but I think it's probably best to not cause that kind of overhead. I released `0.1.1` with regex support, details can be found in the Readme and example directory.

**Comment by podviaznikov** [comment]
Nice!
